#
###################################
# Site wide configuration
####################################
#
title: Ed Holloway-George - Android Developer
email:
description: Android developer and lover of all things mobile security, Kotlin and more.
url: https://ed-george.github.io
keywords: ["security", "blog", "android", "kotlin", "java", "mobile", "androiddev", "code", "development"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/London
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:day-:month-:year/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################

owner:
  name: Ed Holloway-George
  avatar: ed.png
  job: "Android Developer"
  bio: "Android developer and lover of all things mobile security, Kotlin and more."
  email:
  disqus-shortname:
  twitter: sp4ghetticode
  facebook: #username
  google:
    plus: #username
    analytics: UA-141826596-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ed-george
  gitlab: #username
  stackoverflow: 717778/ed-george
  linkedin: edgeorge
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
  medium: sp4ghetticode
  mastodon:
    user: spaghetticode
    server: androiddev.social
